### PR TITLE
blocked_goal_alternative and add small example 

### PR DESCRIPTION
**Pull request by fmessmer**
script to calculate a nav goal alternative if original goal is blocked

### CODE REVIEW

**Comment by fmessmer** [comment]
used in https://github.com/ipa320/msh/pull/138

**Comment by fmessmer** [comment]
Simplest Usage:
- `roscore`
- `rosrun map_server map_server mymap.yaml` (with according map)
- `roslaunch cob_map_accessibility_analysis map_accessibility_analysis.launch`
- `rosrun cob_map_accessibility_analysis example_blocked_goal_alternative.py`

For debugging use [`__DEBUG_DISPLAYS__`](https://github.com/ipa320/cob_scenario_states/blob/indigo_dev/cob_map_accessibility_analysis/ros/src/map_accessibility_analysis_server.cpp#L64) to see checked poses in cv-Display

**Comment by fmessmer** [comment]
@ipa-mig @ipa-srd @ipa-flg
This is indeed an interesting package that might be useful for navigation in general.
Maybe it should be put somewhere more prominent/nav-related.
The functionality (i.e. check-nav-goal-accessibility and compute-nav-goal-alternative) could even be integrated into e.g. simple-script-server or navigation-server in general. It can be used a-priori (as in https://github.com/ipa320/msh/pull/138 or at run-time/online as in the given example).

Please discuss this and keep @ipa-rmb in the loop, as he is the original author and is going to use it sometime soon....

**Comment by benmaidel** [comment]
@ipa-mig @ipa-srd @ipa-flg @ipa-rmb ping
from my point of view, i think this package is quite useful. What do you think? Is it a good idea to check every nav goal in advanced with this tool? Like integrating it directly into the navigation stacks?

**Comment by mgruhler** [comment]
looks useful. However, I wouldn't integrate it by default...

**Comment by benmaidel** [comment]
FR: OK
tested with planogram corrector from msh

**Comment by ipa-rmb** [comment]
Do we put it somewhere else or do we leave this in the current place?

**Comment by ipa-rmb** [comment]
By the way, can someone with merge permissions accept the PR?

**Comment by ipa-nhg** [comment]
FR: OK

**Comment by benmaidel** [comment]
yep the package `cob_map_accessibility_analysis` does not really fit to `cob_scenario_states` repo. I like the idea to put it inside the navigation packages e.g. `cob_navigation`. What do you think? @ipa-nhg @ipa-mig @ipa-rmb

**Comment by mgruhler** [comment]
Would make sense, to put it in `cob_navigation`.

**Comment by ipa-nhg** [comment]
+1 `cob_map_accessibility_analysis` is a new software component , should not be in `cob_scenario_states`

**Comment by benmaidel** [comment]
i've prepared two pull request to move this package into cob_navigation
https://github.com/ipa320/cob_navigation/pull/68
https://github.com/ipa320/cob_scenario_states/pull/18

**Comment by ipa-rmb** [comment]
Fine with me. cob_navigation is public, right?

**Comment by benmaidel** [comment]
yes, cob_navigation is also public.

**Pull request merged**
